import javax.swing.ImageIcon;
import java.util.Base64;

public class Data_image
{
	private static String __img_upload_enable;
	private static String __img_upload_disable;
	private static String __img_download_enable;
	private static String __img_download_disable;
	private static String __img_fresh_enable;
	private static String __img_wait;
	private static String __img_default;
	
	
	
	public static ImageIcon get_picture(String __name)
	{
		byte[] __temp_byte;
		
		switch(__name)
		{
		case "上传":
			__temp_byte = Base64.getDecoder().decode(__img_upload_enable);
			return new ImageIcon(__temp_byte);
			
		case "下载":
			__temp_byte = Base64.getDecoder().decode(__img_download_enable);
			return new ImageIcon(__temp_byte);
			
		case "同步":
			__temp_byte = Base64.getDecoder().decode(__img_upload_enable);
			return new ImageIcon(__temp_byte);
			
		case "刷新":
			__temp_byte = Base64.getDecoder().decode(__img_fresh_enable);
			return new ImageIcon(__temp_byte);
			
		case "等待":
			__temp_byte = Base64.getDecoder().decode(__img_wait);
			return new ImageIcon(__temp_byte);
		
		case "upload_enable":
			__temp_byte = Base64.getDecoder().decode(__img_upload_enable);
			return new ImageIcon(__temp_byte);
			
		case "upload_disable":
			__temp_byte = Base64.getDecoder().decode(__img_upload_disable);
			return new ImageIcon(__temp_byte);
			
		case "download_enable":
			__temp_byte = Base64.getDecoder().decode(__img_download_enable);
			return new ImageIcon(__temp_byte);
			
		case "download_disable":
			__temp_byte = Base64.getDecoder().decode(__img_download_disable);
			return new ImageIcon(__temp_byte);
		
		case "fresh_enable":
			__temp_byte = Base64.getDecoder().decode(__img_fresh_enable);
			return new ImageIcon(__temp_byte);
			
		default:
			__temp_byte = Base64.getDecoder().decode(__img_default);
			return new ImageIcon(__temp_byte);
		}
	}
	
	
	
	static
	{	
		__img_upload_enable = "/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAIBAQIBAQICAgICAgICAwUDAwMDAwYEBAMFBwYHBwcGBwcI" +
			"CQsJCAgKCAcHCg0KCgsMDAwMBwkODw0MDgsMDAz/2wBDAQICAgMDAwYDAwYMCAcIDAwMDAwMDAwMDAwM" +
			"DAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz/wAARCAAUADIDASIAAhEBAxEB/8QA" +
			"HwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIh" +
			"MUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVW" +
			"V1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXG" +
			"x8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQF" +
			"BgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAV" +
			"YnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOE" +
			"hYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq" +
			"8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD9DP8Agmb/AMEzf2bvH3/BOH9nzXdd/Z8+CGta3rXw28O3+oah" +
			"f+BdLubu/uJdLtnlmlleAvJI7szM7EliSSSTXuB/4JPfssHk/s0/s/8A/hvdI/8Akel/4JP/APKLP9mn" +
			"/slXhf8A9NFrXrfxQ+JulfB/we+u63MbbSobu0tJ52ZES3+0XMVusrs7Kqxo0qs7E8IrHkjBmUlFOUtE" +
			"jKpWhSpurUdoxTbfZLVs8Y1n/gll+yroul3d5P8Asz/Al4bSF5nW3+GumXErKqkkJHHbM7tgcKilicAA" +
			"kgV49+yb+zX+yv8AtSar4qsv+GOPhV4Um8N6hLZq2ofDPTDDOsbKCkkgtQkN0hZd9szFlDAqzjeV+qv+" +
			"GuPhT/0U34e/+FHZ/wDxyvKv2X/iR8P/AIKH4if2t8Vfhbcf8Jd421LxLZ/ZPE1s/l29z5WxJNzLiQbD" +
			"kDco4wxrhq4n99DkmuXW+3yPnMbmy+vYf2GIgqXvc6vF3093W91rtb53WhrH/gk5+yyTkfs1fAIY9Ph9" +
			"pI/9t6d/w6d/ZY/6Np/Z/wD/AA3mkf8AyPXdaZ+1R8PvEPi/QdB0TxZ4f8R6p4hu5LSCDSdUtrx4NltP" +
			"cNLIqSFlj2wMu4A/O6Docj0WuynVhO7g72PoMPi6NdN0JqSTs7O+tk7aeTR/Dv8A8FMvCGl+A/8AgpB+" +
			"0FoWhaXpei6JovxK8R2On6fYxJa2tjbxapcpFDFEmFjjRFVVRQAoAAAAoq3/AMFYv+Upv7S3/ZVfFH/p" +
			"3uqK0Og+0fgB/wAHcf7SH7NPwI8E/DfQfBPwRu9D+H/h+w8OadPf6Rqkl3Nb2dtHbxPKyagiNIUjUsVR" +
			"QSThQOB13/Eat+1P/wBCD+z/AP8Agj1f/wCWdFFAB/xGrftT/wDQg/s//wDgj1f/AOWdH/Eat+1P/wBC" +
			"D+z/AP8Agj1f/wCWdFFAB/xGrftT/wDQg/s//wDgj1f/AOWdH/Eat+1P/wBCD+z/AP8Agj1f/wCWdFFA" +
			"H5ZftCfG7Vf2k/j544+I2u22m2mt+P8AxBf+I9QgsI3jtYbi8uZLiVIldndYw8jBQzsQAMsTySiigD//" +
			"2Q==";
			
		__img_upload_disable = "/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAIBAQIBAQICAgICAgICAwUDAwMDAwYEBAMFBwYHBwcGBwcI" +
			"CQsJCAgKCAcHCg0KCgsMDAwMBwkODw0MDgsMDAz/2wBDAQICAgMDAwYDAwYMCAcIDAwMDAwMDAwMDAwM" +
			"DAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz/wAARCAAUADIDASIAAhEBAxEB/8QA" +
			"HwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIh" +
			"MUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVW" +
			"V1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXG" +
			"x8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQF" +
			"BgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAV" +
			"YnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOE" +
			"hYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq" +
			"8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD9Dv8AgmV/wTL/AGbfH3/BN39nzXdd/Z8+CGta3rXw18OX+oah" +
			"f+BdLubu/uJdLtnlmlleAvJI7szM7EliSSSTXtx/4JO/ssHr+zT8AP8Aw3ukf/I9L/wSe/5RZ/s0/wDZ" +
			"KvC//pota9f+J/xM0r4Q+EH13W5vs2lw3dpazTlkRLf7RcxW6yuzsqrGjSqzsTwiseSMEEjxjVv+CWH7" +
			"KmiaVdXk37M/wIeG0ieZ1g+GumXErKqkkJHHbM7tgcKilicAAkgV4/8Asofsyfsq/tQ6r4psz+xz8KfC" +
			"s3hzUJbNW1D4Z6YYp1jZQUkkFqEhukLLvtmYsoYFWcbiv1P/AMNZfCv/AKKX8P8A/wAKGz/+OV5f+zF8" +
			"RvAHwW/4WH/avxT+F9x/wlvjXUvEln9l8S2z+Xb3Pl7Ek3MuJBsOQNwHGGNAzQP/AASc/ZYJz/wzV8Ah" +
			"j0+H2kj/ANt6X/h09+yx/wBG0/AD/wAN7pH/AMj13+n/ALUvgDxB4v0HQtE8V+H/ABHqniC7ktYYNJ1O" +
			"2vHg2W09w0sipIWWPbAy7gD87oOhyPQKAP4df+Cmfg/S/Af/AAUh/aC0PQtM0zRdE0X4leI7HT9PsYUt" +
			"rWxt4tUuUihiiTCxxoiqqooAUAAAAUVd/wCCsX/KU39pb/sqvij/ANO91RQB9ofs+/8AB3P+0j+zX8Bf" +
			"BHw40LwT8EbvQ/AHh+w8OadPf6Pqkl3Nb2dtHbxPKyaiiNIUjUsVRQSThQOB1/8AxGrftT/9CD+z/wD+" +
			"CPV//lnRRQAf8Rq37U//AEIP7P8A/wCCPV//AJZ0f8Rq37U//Qg/s/8A/gj1f/5Z0UUAH/Eat+1P/wBC" +
			"D+z/AP8Agj1f/wCWdH/Eat+1P/0IP7P/AP4I9X/+WdFFAH5Y/tCfGzVf2lPj744+I2u22nWmt+P/ABBf" +
			"+I9QgsI3jtYbi8uZLiVIldndYw8jBQzsQAMsTySiigD/2Q==";
		
		__img_download_enable = "/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAIBAQIBAQICAgICAgICAwUDAwMDAwYEBAMFBwYHBwcGBwcI" +
			"CQsJCAgKCAcHCg0KCgsMDAwMBwkODw0MDgsMDAz/2wBDAQICAgMDAwYDAwYMCAcIDAwMDAwMDAwMDAwM" +
			"DAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz/wAARCAAUADIDASIAAhEBAxEB/8QA" +
			"HwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIh" +
			"MUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVW" +
			"V1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXG" +
			"x8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQF" +
			"BgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAV" +
			"YnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOE" +
			"hYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq" +
			"8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD9C/8Agmd/wTP/AGb/AB9/wTj/AGfdd139nz4I61retfDbw7f6" +
			"hqF/4F0u5u7+4l0u2eWaWV4C8kjuzMzsSWJJJJNe4n/gk/8Assnk/s0/s/8A/hvdI/8Akel/4JP/APKL" +
			"P9mn/slXhf8A9NFrXrPxP+JelfB7whJrutzG30qG7tLSedmREt/tFzFbrK7OyqsaNKrOxPCKx5IwZlJR" +
			"TlLRIyqVoUqbq1HaMU232S1bPI/+HT37LJLA/s0/AHH/AGT3SP8A4xXn/wCz7+wv+y18dP8AhN8fsq/A" +
			"HSh4N8WX3hf/AJEfSJ/tn2by/wB//wAeq7N2/wC582MfeOa911f9qr4XalpN3bwfFjwNp89xE8SXVv4h" +
			"09prZiuBIgkZkLKeRvVlyOQRkV4X+xdrGhfs9av42ufFv7Qvw28RQ+JdbudVhtbLVdPghmlmZDJezHh0" +
			"mcIo8lGMUYDYLlgU4auMSrQjFpxd76r5db/cfOY3PYRx2Hp0Zp03zc7UoWWnu3vLm37J+Z35/wCCTn7L" +
			"JwR+zV8ARj0+H2kj/wBt6f8A8Onf2WP+jaf2f/8Aw3mkf/I9dxpX7U/w/wDEPjDQdB0TxZ4f8R6p4hu5" +
			"LSGDSdUtrx4NltPcNLIqSFlj2wMu4A/O6Docj0euynVhO7g72PoMPi6NdN0JqSTs7O+tk7aeTR/Dx/wU" +
			"y8I6X4D/AOCkH7QWhaFpWlaLomi/ErxHY6fp9jElra2NvFqlykUMUSYWONEVVVFACgAAACirX/BWL/lK" +
			"b+0t/wBlV8Uf+ne6orQ6D7T+Av8AwdvftIfszfA3wV8NtB8FfBK70P4f+H7Dw5p1xf6Rqkl3Nb2drHbx" +
			"PKyagiNIUjUsVRQSThQOB1n/ABGrftT/APQg/s//APgj1f8A+WdFFAB/xGrftT/9CD+z/wD+CPV//lnR" +
			"/wARq37U/wD0IP7P/wD4I9X/APlnRRQAf8Rq37U//Qg/s/8A/gj1f/5Z0f8AEat+1P8A9CD+z/8A+CPV" +
			"/wD5Z0UUAfll+0J8btV/aT+Pnjj4ja7a6baa34/8QX/iPUILCN47WG4vLmS4lSJXZ2WMPIwUM7EADLE8" +
			"koooA//Z";
		
		__img_download_disable = "/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAIBAQIBAQICAgICAgICAwUDAwMDAwYEBAMFBwYHBwcGBwcI" +
			"CQsJCAgKCAcHCg0KCgsMDAwMBwkODw0MDgsMDAz/2wBDAQICAgMDAwYDAwYMCAcIDAwMDAwMDAwMDAwM" +
			"DAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz/wAARCAAUADIDASIAAhEBAxEB/8QA" +
			"HwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIh" +
			"MUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVW" +
			"V1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXG" +
			"x8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQF" +
			"BgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAV" +
			"YnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOE" +
			"hYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq" +
			"8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD9DP8Agmb/AMEzf2bvH3/BOH9nzXdd/Z8+CGta3rXw28O3+oah" +
			"f+BdLubu/uJdLtnlmlleAvJI7szM7EliSSSTXuB/4JPfssHk/s0/s/8A/hvdI/8Akel/4JP/APKLP9mn" +
			"/slXhf8A9NFrXrfxO+JelfCHwhJrutzG30uG7tLWedmREt/tFzFbrK7OyqsaNKrOxPCKx5IwQUdjyIf8" +
			"Enf2WSzA/s0/AHH/AGT3SP8A4xXA/AD9hP8AZa+OP/CbY/ZW+AOljwd4rvvDH/Ij6RP9s+zeX+//AOPV" +
			"dm7f9z5sY+8c17vq37Uvww1HSrq3h+K3gfT5riJ40uoPEFg0tsxUgSIJGZCynkb1ZcjkEZFeG/sZavoX" +
			"7PureNbnxZ+0D8OPEUPiXW7nVIrWz1XT4IpppmQyXkx4dJnCKPJRjFGA2C5YFAZ3Lf8ABJz9lknI/Zq+" +
			"AIx6fD7SR/7b07/h07+yx/0bT+z/AP8AhvNI/wDkeu70z9qXwB4g8X6DoWieK9A8R6p4gu5LWGDSdTtr" +
			"x4NltPcNLIqSFlj2wMu4A/O6Docj0SgD+Hf/AIKZeENL8B/8FIP2gtC0LS9L0XRNF+JXiOx0/T7GJLW1" +
			"sbeLVLlIoYokwscaIqqqKAFAAAAFFW/+CsX/AClN/aW/7Kr4o/8ATvdUUAfaPwA/4O4/2kP2afgR4J+G" +
			"+g+Cfgjd6H8P/D9h4c06e/0jVJLua3s7aO3ieVk1BEaQpGpYqigknCgcDrv+I1b9qf8A6EH9n/8A8Eer" +
			"/wDyzoooAP8AiNW/an/6EH9n/wD8Eer/APyzo/4jVv2p/wDoQf2f/wDwR6v/APLOiigA/wCI1b9qf/oQ" +
			"f2f/APwR6v8A/LOj/iNW/an/AOhB/Z//APBHq/8A8s6KKAPyy/aE+N2q/tJ/Hzxx8RtdttNtNb8f+IL/" +
			"AMR6hBYRvHaw3F5cyXEqRK7O6xh5GChnYgAZYnklFFAH/9k=";
		
		__img_fresh_enable = "/9j/4AAQSkZJRgABAQEAYABgAAD/4QAWRXhpZgAATU0AKgAAAAgAAAAAAAD/2wBDAAIBAQIBAQICAgIC" +
			"AgICAwUDAwMDAwYEBAMFBwYHBwcGBwcICQsJCAgKCAcHCg0KCgsMDAwMBwkODw0MDgsMDAz/2wBDAQIC" +
			"AgMDAwYDAwYMCAcIDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwM" +
			"DAz/wAARCAAUABQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAA" +
			"AgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRol" +
			"JicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZ" +
			"mqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QA" +
			"HwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSEx" +
			"BhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RV" +
			"VldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPE" +
			"xcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD9AP23vj78cfCn7Vmt" +
			"eGvhb4mvNbtbTR7fWJtH0vR7O8udKVmSB4yrI8sjF2jlxjcEuB8uxd1fVv7TPiT4h+D/AIOzax8PLLw/" +
			"qOt6YrXV3aarFczG5t0hkZo7eOD5muGcRhVPByR1Ir54j+O8P7MH/BTnxjpHiHRb+W3+Lf8AYcej3VpJ" +
			"G5VlQWiNIhYERmQzAtncPJGEYMCPRf2pv2/bL9nH4uv4JuvDGoa1fah4fj1HSFspS8+pX0t01vFZLGEO" +
			"3O0uZNxOAQEZiqt4tOtCMasqlRrVr/C+lvXc/OsNjaNGnjK+JxMotzcLXfuP7Kjo99z1L9lv4yx/tAfA" +
			"Hwt4uV7d7jV7FGvRBE8UUd2o2XCIr/NtWZZFGSchQQWGCSuc/YG+DutfAb9lLwt4Z8Qpbw6xaLPPcRQy" +
			"+asBmnkmEZboWVXCttyu4HBYYJK9Wg5OnFy3sj7fLJ1ZYSnKt8Tir+tj03WvAui+JNRtbzUdJ07ULqxw" +
			"bea5tklkgxLFMNhYEriWGF+P4oo26qCMbxz8AvA3xO1iPUfEvg7wv4gv4oRbpc6lpcF1KsYJYIGkUkKC" +
			"zHHTLE9zRRVzhF7o3nh6UotSinfXZb9zrY4xGuB0ooopo2Wx/9k=";
		
		__img_wait = "R0lGODlhQgBCAPcAAP///z5Vh3eHqpqmwOTn7ra/0fn6+1NnlNDW4QAAAAAAAAAAAAAAAAAAAAAAAAAA" +
			"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
			"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
			"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
			"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
			"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
			"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
			"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
			"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
			"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
			"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
			"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
			"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
			"ACH5BAkKAAAAIf8LTkVUU0NBUEUyLjADAQAAACwAAAAAQgBCAAAI/gABCBxIsKDBgwQFHEDIsKHDhwUJ" +
			"HChg8MDCggUOGIDIsSNBiRcJWqx4gIDHkxANWDQpMqRAkBtRygQwYIBBhRRbFhxwQIBBAjFnMlR5AAHG" +
			"ngVHJpxY0AABlkIZZhQQFABMnQOJQgXgFGjUhgYU2mxpdKBSgQjOCuxa9avBtCUJ8swpEOlAnmPXPm0r" +
			"lMAAvmIJIhBQFuHgwlyfGnTK9yFPqhFXRmXb9OlWjmF7Xp47WTHBrl5RZoacFUHjjgZSf7Z8OqVCAZfd" +
			"Vt77dXTr2gQQhK6tELHsrLQ9ZizA1+lvhKpnxxaYsafv4x6d6l7+UqFm6NFz676N1vpf7A67/m7nnrVA" +
			"b/Bgc+/umJs8dMbo43P0LF928tcDClCvn157WfOv9TTAfvzphcCBB9JnFQIDvOZTgQz5B9RtBOgH4VDr" +
			"Xajhhhx26KFbAoTYU4ghfigYgigy6GBPB+RlYooomijjjDTWWGCFz20IX4QFNBiiix0iUACC6wFIogAW" +
			"mijdkEPqJpCPQ7qnoXhD6mUjWFJe+VCFWdqXYUoAEghehVFiNliIxOmIo37cqYhkl+8JOeR+AA6QI4cG" +
			"yEldj6YtdudvX0on5mINDjqTAQWk6ZYBDX6HHqJlTtYonCdBqqhMjArg6Fp9CrUjp4lSytWkGNkZlZC+" +
			"5RkqSuZt+lKhcJMlehmkfw516V35fTRgQxVuJaefoh7kl6t8EpSoYKaWl+SjDfpW01Y1fZarYKuix6Cr" +
			"jLoabXnYysrsrsjS9SSQDF5GZrAOVVmqs+QeW9CBU9bU1rZZ5YeubMMaRO9APd7rFo76AgmAkP7G5y54" +
			"AQEAIfkECQoAAAAsAAAAAEIAQgAACP4AAQgcSLCgwYMEBQhAyLChw4cFCQgoYPDAAYMFDhiAyLEjQQIW" +
			"K14saJGAx5MQDVjcSDDkx5UoYwocMMDggAMUW44cmLFmQZoyHRoQcABBwZ4kdwok6nMgApdBGWYUwFIg" +
			"SI06Cao8YHLg1qZRDw7FWZBoV4FQAVz9CTMsw6dcCd7MuXThwJtgtxp1q3ZA1btkB0rcixCBAMIAbtr9" +
			"OAAxx6l/1ZaMCveswK8ohyq0DCAj3Zh4I1rEmpkoVa0IIp80UODvVtIxNZ/mi/AqbJljZ9PWalF3VM2O" +
			"d8NV7bDARNUGgu8GkNqgAQMEiHc+oFD58pQECCDg/FHhgQHcr/4zhJ49+kPjTKWLv0w+u/qCrKuvH7/d" +
			"/Ent78U/zz+/v9rw/sXGkkICDFAAgAGOR952AhUwAIEKgZdgQwtuV99HCDwY4YQMZVffcw0RcCCHCEHH" +
			"H4kopqjiiiw2pCGEBbYoGAI01rjdixCCxaJ2NtKIoIxABinkkFGJaB2HJoaYoYY6pmijewQ5mOOILULX" +
			"I4OJFVhAc0RWuBd0RCoYJl/4oZjkalL+KB6PXD6U3IMGnrhbcjXa1yGcfrFIJ43qGUeTmhNqtyWAGbbp" +
			"FaBFIqcdolr9OR+PcgpFU57rJbdlpCVOimlmCFwalAGaorYpfHYCYKmhHYFKU2SFFrklfHedogqRg5QK" +
			"5uinBbQGK5Uesaaag4iJ+KOwBMXqXKlFrlpsY1F+ZqRWuTIaG02OOfiXgR/lGpGn62Woq1fK8pRXrq51" +
			"Km2vt9rqGLbF8noZud0G5yBnDm4bXHYkslbrTJ+ZCm+LBLAbZZPRyshacAIL9u2Y2q4XEAAh+QQJCgAA" +
			"ACwAAAAAQgBCAAAI/gABCBxIsKDBgwQFCEDIsKHDhwUJCChg8MABgwUEGIDIsSNBAgcWFrRY8QABjygh" +
			"GhBgcuTFjxY3ppwJYADFggMmuixY4MAAgwN+0my4UgACnj53Ehxw4OZABCSHNsyokaCBkDIFRhV4teXA" +
			"rk6lHiwaFgDLkwO3AgApcmDPqmIZQoUrsGfYnAR7CuVq8WjctQXQLhWwd60AwQcRHF4a0qCBAX49Us0q" +
			"UOLioSC9frVYmGPRAYgB2JWqt2DXyyiL0gVgAAHllK0pS4w59LHC13+tWjyAO3XO1bn5Yv1rO3JwgXND" +
			"P8xYALcB5cddOy59kCrk4zShcmZI4Ddo7B1n/vd9qFhhc/BEmXLuPZaqcfRIfbJvSEA6/Pbv7+uPCH1/" +
			"SgRo5RQUgP55REBGuyH3m0I29VcgAIrtthtirRXg3YMISUgAAfOtRSCGjhnQIYgklmjiiSgCRdiKAqZY" +
			"2YYwwhgUi4R1ZmJ9OAL4oYs89ujjj3HhmOJzHVYYVFAp5sghZQgcWWNgQ8Ko44YCHVmAfT6KuOGHzwGJ" +
			"kIhexhUbiETCZuF3GLYG4IhfNTkgm8c9hwCAHDp0YFDnmSjnmgydCaWLe/bXJJZfOUicczCmZqGhUqkJ" +
			"50MGWJgneGoSOlOkNj1K056aTpepVXXWFipXc1rqmaSvIXClVEJaVWqncgpOylWDjar6mpyMHlQfbhYa" +
			"F6mhu340p2OjinWgrKoipupHq7a5I6WL8iRrAWFF+l59puamqqyRTlutra4+G9xjfz7VrFtlJWvalbBy" +
			"JC6E59ZVFrYGUflgt69Ru262aeorrUHgovgrRmV52G6Bw6IXEAAh+QQJCgAAACwAAAAAQgBCAAAI/gAB" +
			"CBxIsKDBgwQHCEDIsKHDhwUJCEBgUMABgwUEGIDIsSNBiQsLCghJ0CIBjyghGhi5seTFjyxTyhRYoIBB" +
			"hTZLkhSI4MAAjD9nNlwp4CRBBAKCDrRYcMABikcP7BR6EOmAlgKJYgUwkiBRo1kt5qSK0ABOkUVdfpRa" +
			"sIDUrWQNgtyacSyAAUoBZMy78mlcgQQKwL0rwC6BAVARIgV716dBs4w57oX7larEA5Ev5+VoNincjIll" +
			"urULoK9GmZ2vekUw2KMB1jDfCk3d+m9Y2VRp235s8XTczpF39/TdsQDiwQaC7wYAu6CB0YqTIl4+E+kB" +
			"xwgPJy2gnHp2i1JD/itWOECw96FOr5tXabX7eb3XVaN8Xfv9c/fv8w9Mrt82AqN4lddcfx0FBl5ICAQY" +
			"IHcENpTgdRAeYNdrxuFFWoMuXVcYfgT8h+F4+H0o4ogklmjiQxUqWN6JA0XoYooKXkgieC5OxeKNOOao" +
			"o20dhthfguI5h0BNFrIY4YZHGVdhAQOW+KCLQSnJXX0lGghhVlTqSICPO3LWJIEGhJkShQx+mNyWWe43" +
			"pIBpLncmmlkGVtOXZm6JJkND1sRlf2/WNiSd/OUnpnNnzqenfXf+NmebqPXIKEPP1fRoo4mitqhXBEz6" +
			"2KBZOWqppBGVOVOPztmpKXNMUgbqbB1S1uqYX3T+uRqV9H3kYamnZpdqkowhEBqp+71q35CRDbmVr6uJ" +
			"91qm7wXW5HNNIqvms8BSFylcHYrHZES3qsmsd1sa5Gux4lUbrJnGFiTttLnuBq24F/rarm3LihtkpV2u" +
			"S11AACH5BAkKAAAALAAAAABCAEIAAAj+AAEIHEiwoMGDBAcMQMiwocOHBQ0MKGBQgACDBQYYgMixI0EC" +
			"AhYWtFhRAAGPKCFKFLCRIMmPFlumnFmAYsECAhCMvEgQQUiMNmc2lDhAZ08BQQW+HDggZ0GfPIU2RKBQ" +
			"JgADIa0uvWrx5ECsB5JKPbjSKFOTLqMCAKkWAE6WYx2C1EgQp1kACusiJYjVaVyBBApYFYgzKYEBXhEe" +
			"vttUJF/EKTPS/agw8Uy2lrn+RGlA8mC7Y3E6FggWbkqik0kTGMwZgdW+pmd2rvp3qIADsYWiZl1bc26p" +
			"szP3BoAAN++pRVkbED58rfICYRFSrdxcqM8D0RVLLsC8uuIB2P3+Ilco2PtQ8LjLq5ze3Txx3Kk7GnDt" +
			"HmHn9vXzX8WvvyMCrxnVRF9/HQWGHk8ISEaeegQeRNVt2KXHFwEJktcgQhAeMBF+8/GnX4IeXijiiCSW" +
			"aGJDNU2kYk0nDpRhhOkFGOBELSoFY4Rt1ajjjjz2CNx/LVJ1l0HLJViTWCNmiJRlRh5ZwIAmUnVjdkci" +
			"AOWOgWVI2nE+ruZjbctxaZ5EIUZkZJm9QWccR8sd6eWFEkXIoGJGXikiSBEO+ZGAaNanpobScadcnykB" +
			"GRF0o603Z3PFHUCofQnaOZwBEYqpqKTNUYrdo19F+tqbuhnwGoSWQvrkYBRy+hUBmWnqaEptgdk536Kc" +
			"sTqYpomqBOpAVlo2n5hhfsQqkZCBaaVVqX50V7Kr7lrdrJkd29Ndy2XGqrPDUXjlfFdaOeG2to4prbLR" +
			"Dknhrf+VeplwzPI6ZIdEqirbuO6aia2I3BrkbUHntgjvU3oG++Va8joUEAAh+QQJCgAAACwAAAAAQgBC" +
			"AAAI/gABCBxIsKDBgwQHDEDIsKHDhwUNDEBgUKFBBAMMQNzIkSABiwUFLCw4QACBjighSsxIcuRAAyI1" +
			"ppwJAAHFggUmhnQpEIGAAgYLAKXZcOVJghiHDgQ5MOfNgT55Ej34sYBMgSuvAhBJUKIArV6VTj1owGnL" +
			"owKZAiDAFWnMsQ0/soSqcynPpF0FCHg6lgACrQLNDiRQAC3VAYYL/DRY1vDGpICNTmVrMqJesRvLCgWM" +
			"kW9Kn569zkVZdoDVrgQAk/6b9y1NzafhMhTtOGXp2LItux6ruXZutqMfF2Ad0XfutarLLj6IQGjh40R9" +
			"XmZI2Llq6HFL6vVM1Tlx7LMV/l++Trb5c/AMERz4Sb7od/SMERiHTx91/dzyAwuV3/4+QsLaCSCQX87t" +
			"159/H+m13npiGUCgc/41pKBIuJGVWoTUnYfhhhx26OGH+BXoHYgEKXjAgus1p+Jww5E4kAAnwhijgC7W" +
			"aOONOILn4HwRqliUXypyx6GMB5hmGIFBvudhgifGOJRNNl2YY2kw0mjAgTcSwGOOHTmIJXQSbWmhTV8e" +
			"p16RYmIFJH8cStRkheVBWSZ4H8Uo5IBy2ujTiVINxmZEc86kJABlHYDZQwaQCd+Zgc4WZaMcwbRemj/+" +
			"CZ8BMVIa53tXQtpVhZIe4GmiluKp6UEDFFkQW5Om5JeUcC+V6uqJnrHaJ6Kw+mmYlw0pxleVBn10qnu5" +
			"anlkYut1deKhxzmopJZaaYnUiTid6ClEr4LlV7S7nrgrjLfC5Sxgxq7qGIyYMYpergOyKy1BBSSLU7jo" +
			"7UiuYwRY66KzwdZG677srlVbScNi+C54AQEAIfkECQoAAAAsAAAAAEIAQgAACP4AAQgcSLCgwYMECxRA" +
			"yLChw4cFDRRAYHDAAIMIBhiAyLEjQQIDFha0WHEAAY8oIUrUOPIiQQMWN6acCQABxYIKbw4kSTCjyJ4/" +
			"aSKUWODkx5AtcQ7QKZCAAJdCGSJQKFMgzAJVAfC0GvOlRaZRDRIFW4DlTqgAQKKt2TUsQwJUey5NGNSn" +
			"VwFG3RpAkFVgzo9YG8LNC6BsUKtFU04N/LJsX5QGnhIGAFPAYZWL+04Fi9LuXbOQM78k8NijAdKfS3Mc" +
			"q9ot16etVytk7DqiRdBR9yauXdApboiDHxuI7RZ1RASWEcKdOJm3x4wCkg9dzNe56QHRTT5cPpG4dYnZ" +
			"af47PK2wufWCyC17F2v8/HTz7uMfHC6fNwGjmxG0r99xZfamm01k03rygRTdgdJZdd9EE/HnEHbZVcfQ" +
			"aQTGN5iDGGao4YYcbmjThyB2WNEBCB5oE4P5iTgSiSwKcMBaKsYo44w0OkihjFPBpyABIcboYniE8Qii" +
			"fhW6Z2CL0n14X5E2lvWjVUyKuF+Nek3Jn0Q6TsijlfUhcMCLBJ4mJJfyVfalePONGWVtIH0pAGcDqUkj" +
			"cmcqt6RYa3YkYWMJrsZjng95KQCgoxEZX2QkZqnSfWTWhiheQp1m6EDDESpRVo+uKeaUdwpVwIsR/ajo" +
			"QYz2JSahBHw5GaIwPnRjb2739XQAnAMhx9QAJIqlnWunEoQrWrkO9ClaBnxJK69/FqQqQV/KegBOJBLa" +
			"UK9xfplVs5QuS6mLreo16U7BDoTtQC4e5uUB0g71WLnKPptQuMJeVqa24rpbLbo4jluvQcbKmOpl+voF" +
			"KZUEuRhfQAAh+QQJCgAAACwAAAAAQgBCAAAI/gABCBxIsKDBgwQLFEDIsKHDhwUNFCBgUKFBBAUMQNzI" +
			"kaDEhQUthhygsaPJhx9LDiwwIOKAjCdjCiSA4OLEkCAHEhhQsyCCnjIZGsCocmYBoAJFDkQwgCLBnS2D" +
			"NiRwtGhKgi89srTKEqlUg0NvJoS5MicAA1kJMiX7FeHVpWKTmt2JVGLTtgKHFhX4sy4CpwipFl0LNi5H" +
			"mgj2vpWJlmTErifDJi5IFXBMpl4bO47c16qBvSYNEOD6EjRHyabx5h3AOvXpzqoLl8Yb1vVXqLYP0hwN" +
			"Nvdt0EN5BoYdWybUtAeHEi++kSrruw4R//Vd3C7ryRBF/6Qem+ns0LyZ/jccalm8eZTczzd32pdAePUm" +
			"aRYQwHqm9J/v4TN0Tp8+8rPa9aWfQ6zRV9V4+Q1oUGUKNujggxBGCN997UlY0AACZKghfbv95WF5EmLY" +
			"n4ZRWWjiiSim6KBo6ZmHEYgeibYbjA6KSN9fT3XoXoIQQrWhACDtOFqLA9IkYlSfqRgdkUqOl+SKhm30" +
			"mXtMSoVAhpuhJ2SVQaGlIVtubWnhThp6lSOVKV6ZoVkeDVkYfNhpBWRoBxxgpmpqcklZnQfo6ZABAhwg" +
			"gJ9n8UnonxrqSYChWvkpkVUa0vgno1gdUGJM8116VqInDVDnXovaKVWo5QF6AJsQMQVanZdeeedSawIg" +
			"JWJhkpqEQJ2WeXpphglZ6lGgr9JWJ5u4ElTnU4KGJOihCBXwKbJ9GnuAR8UOBOic4hlQp1fOanpspWze" +
			"Oqh5/wkUKLHT9qopAEoNqO0B5X1r7bMmhmqQvAMFWmuR2EpbkQD7WsireQEBACH5BAkKAAAALAAAAABC" +
			"AEIAAAj+AAEIHEiwoMGDBBEgQMiwocOHBQ0gIGCwQAGDBAoYgMixI0GJCwsiuChSo8eTECWaJFgg5EAD" +
			"FjeinAmAAMWCBCaWxNnSoEKaDkHKHJjTpUCLJW8SRQq0YdGhAIQmJCkQ5sqqFpU2PQhSK4CRUHu+FLv0" +
			"6lauCqHm1PpzqVGrXoEaIABV4NqPCOpG1DlwpNGqfD2urStVbsyIFv+mfIoz8Ey/iA+jnDsRqoHLTeda" +
			"LjDA7EnKec82tOp58mDRXC2WnklZL+qMq0fn1YsZ9UG6BlUqtnvaNs2MAwbsrloUt++OMIMXiJt7rfHj" +
			"DCUqD704p2voRINT93j5Ovaoz7/+i4/uffxJ4zZt1jaPfGTwAcQnTlTP3qnF953fXp7PvP7R9y2Vp5l/" +
			"CN1F4IEIJqjggkCl56BNDA6E34QPOhjhfwIMkKGGVF3o4YcghrgVAsJFqFB/dhUgwAEsHhBhcBm2pNUA" +
			"LbY4AIr1AZfhhiG1KMByIqqkIXw14QhieCI2OEB50MFkJFc0HtAhewjEyORLUR6w5IEwCeDldghVyaIA" +
			"T37XZYbDAZBlmgQSoOGPCNFYmkTjgQlYZ5+xyGZTBGR4JUR9HiDAn6y9SWh0Yx5aqJ8NrkjmR7FxJJFl" +
			"hrKWaEFyNqXilG4yehKNjxJEAItlMtRnqFjCed6WBa1IpEBtVbJZ5YwZYgSkaAiwCFWmA3nJUq0vfSme" +
			"AStOuaJWKybk66+DfleAoGpBSxCLH61IqarHGaBnQc++KlCyBHEokpeKdsRUuFIWJCi3wLI05XjEHuAV" +
			"tR9Jy+CoAhi0bquoKtjnu/T+WiqC7R4XEAAh+QQJCgAAACwAAAAAQgBCAAAI/gABCBxIsKDBgwQRIEDI" +
			"sKHDhwUNICBgUKFBAggMQNzIkaDEhQUthiygsaPJhx9LDkRQIGKBjCdjCiRAsSDGmitBDsSocyVOmQgN" +
			"YFQ5c2LIngAU/gRAoEBLoA0lEiCakuBLjyypslwKNeLNo0RFCjRwlWBTmF0ZVt1pNKfZAj/Jwk07durF" +
			"tmPRBtWbVOxAiUQ30rTrcShUuYHlIoUodGJgw0CbLlUceKNQmlQNVO4oVKvTzZZvgqYLQC7JrpcJk/bo" +
			"lC/QxqNRv4x9EHNlzatr32a5uK7j3DKbtlY7WDVwlE6dcjWY2vhx5ixb0/47eHpuAgNmn9RsfXXn5+AF" +
			"/vcOH7zkgfMC5pI3KdFpdoEFzss/IGD8erYFsg/I3rOpAPkC3NdQftnBFRsCA9gnIGQCNujggxBGCN58" +
			"FEpYEIH7ZVjAfxTSZ6FVGYb41IcklmjiieQhqOB9XzHkH4AkishXfBQmSGJTIe4HEoDqodhehjMth+JO" +
			"3Q35UFNF0iXVdgOcN6KACKbXHVnyDZBkWmRl6FpFHAogJIsb7vdlk/StuOB+9SHU5GkRmQnVlhK91xEB" +
			"/7kZE51W0kUnfVdyZMAAAuQJ1Z4C9MkZoILe+V+hrBn6F19/BmoooYGtCdWGT5aGaJ9NMmoWfV9CRKeX" +
			"EQGaqagDcPXfAGalyRCCaD+FyVyPXSHAJ0GmEiRAgAPJ+teuoaL2X6b//bRrq7yuJCl48Xk6060D/efR" +
			"rlTlepwBxV4YaEEe4pqeTdQ+55RBluqarEAIbDuSg9geEFi3O4X7IQHwRnuAQcCSiO2px16YqJHqHhcQ" +
			"ACH5BAkKAAAALAAAAABCAEIAAAj+AAEIHEiwoMGDBAkQQMiwocOHBQ0oNIgAgUECCAxA3MiRoMSFBTFe" +
			"zNixJESJJAlWjFhRo8mXACReJOByoMiECEAm1AkT4ceaAg3kLLgSJ8+YRXsy/OlRIdCbQVt6rHhUaUSn" +
			"IVMKTIrUIk6tVg8yHSj0KU+MPIWCVYpgQFWFaWk2lPiUa1C5JQccEHB0LEy1QJEWqPrQwIHDgT8qRcuy" +
			"wNqNhg+nNRC4JGWgah9zjHygctipjj135Cw6bObSowUc8Po5Yui8BwZUhto6YmWJgxHqPVygdk+MBXIj" +
			"RHB4L2HfSxEE11ywQHEBqJHHJLAc70MCu1lLP0h9cPSDyr/++6a7vfxG2uat4n0uPP1o4MEFFlBdPLZ2" +
			"92KVB99/dv5z/A3t55h13A1wH4BNiYfgggw26OCDHNFX314QEiTghRLWJ0CFAwU3QAEfftgbhySWaOKJ" +
			"0il3IIOMMUTdbhRWCCJ/QA2QoQBucQhciB96Rd+HCiKo1ox3obhUkEY2RB2Spg1lWXYsDmCgggb4d0AB" +
			"TFollJRTOoTAj8fhV6WU7Rnk3F4rNviigQg595hQ6REYFZupCZBmWNjJ9pkBqkFXngFkZhmSAIQKuhmX" +
			"hsbUJ2bMQQbWmHqaRAChfhJk44gwtYVpUIiaZGOlNhEaJkTYgRoUkSVhVxmhAyREJ0Jm2PEEYquuJUpU" +
			"oRYKsKmUuW4KaI5/EropAKISRKhHON4aqXTzmTqpqceSZSNmUt6pFJ98KVtQtB3aOeiyvsVXkI33cbuV" +
			"rhRZixy2R5mrKLgOPmuQuwDYOCp+2B1Ib1u2msfrdgEBACH5BAkKAAAALAAAAABCAEIAAAj+AAEIHEiw" +
			"oMGDBAkQQMiwocOHBQkcKGBQoUEDBAxA3MiRIIIDByouLIggY8eTEA2AHDnQIkGMJlHKBDBggEEBEyOy" +
			"FAhT5EyHKnMSLHBAgM6ICDS+LPnTIdEDSgVKhJpwJ8yoAGDubHoRJEWCIBEkFDsQI9mWJbFyNfjxwE6c" +
			"NlvuVGiVQNK1AhEM2AoAbsIDZw9ixGqX72CUA4qqbcu3o1m1BhAwPWkAJ1WCiePOtAu5sNqNBCxjNVDg" +
			"s2MDoyXfnVm5aGO8PD1zDSrANN7Ikm1TxhkYNs+0JxOXvtjbN8/PZl8/BWycterXABBYFgC9OXHVugcu" +
			"H5DdulnJMR/+GkjM3DpDu8BPEhhuHuHh9vAd2o0PG7VAywMKVKcvGH0BsgVYBpIAAxTH31KS/fefVQWQ" +
			"V9SBDCVYUngHrWcghFlRiOGGHHbo4YcoCQjSgCAOhEABKKb4nwA4tQiSZiCeKKOCF5Zo44045siVjCVy" +
			"1tB6A7RoVIwppidQgEUVReB+9EWmIoojsUggezmalaJUTN5on454rdddc5F9eVGQAtRo3nr/iZlVgCxS" +
			"eWBk+enXnXQs7vUhnFAyxGaZN6L5H0IBuvlbfBpm+GdHBARpZlOJCspanWqiRBqKkboHaXyk5VdpQZUt" +
			"udSmnFKYqaMpXTqUAF/NpFdvo4IaoJ13CbEIakI1bZXpohU6GmSqACRa3Xo76cXrb7MeJB13pwZWk0f5" +
			"vVQrfOPxiRl1mMGYKIy9atreq6MRiBWBziJbVoO4ytTpVtINC+5QBUZUU7FOFRdgb8syO2x05dYXpFrr" +
			"lvVuj/0OFKRBz4I4XnEB50XqjQ22FxAAOw==";
		
		
		__img_default = "/9j/4AAQSkZJRgABAQEAYABgAAD/4QAWRXhpZgAATU0AKgAAAAgAAAAAAAD/2wBDAAIBAQIBAQICAgIC" +
			"AgICAwUDAwMDAwYEBAMFBwYHBwcGBwcICQsJCAgKCAcHCg0KCgsMDAwMBwkODw0MDgsMDAz/2wBDAQIC" +
			"AgMDAwYDAwYMCAcIDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwM" +
			"DAz/wAARCAAUABQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAA" +
			"AgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRol" +
			"JicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZ" +
			"mqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QA" +
			"HwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSEx" +
			"BhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RV" +
			"VldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPE" +
			"xcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDuf+Luf8ELf2t/+g34" +
			"W1v/AHodM8YWCN/wLyLqLf8A7Twu/wDy1hl/fe9/8FCP+C6WmeKvhJY+HPgheara6r4lsVl1fW57d7S6" +
			"0BHGGtIQf+XrqGmQskY5id3YSQn/AAXS/wCChHhHxV4ZvPgh4csdK8S6ra30U+t6vKglj0C4hfIt7Vh/" +
			"y9feSVwcRo8kXzO8gh+MvCHhD4g/8E0v2gfht488efDb+5renadrca+TfR7dpGV3eRdRb1cK4823l8l3" +
			"j+6rfmOKxVTBVKmDwdR+xuruzfJd6pP+vvuz/QTh7h7BcV4LA8U8U4GKzNRm6dNzjD63yRThKUGvTpZK" +
			"0pJ03GK+kP2af+Dfbxd8XvhJp3iPxp4x/wCFd6rqmZotEk0M311b25AKNcEzxeVK3JMWCUG0MVfdGhX6" +
			"kfs0/tLeEf2s/hJp3jTwXqH27Sr7McsUgCXWnXCgF7a4QE7JU3DIyQQyspZGVmK+pw/DOVypRkoc11vz" +
			"PXz0dvuP53zvx/8AEOjj61KpiPYSjJp0/ZUvcs/h9+Dlpt7zb7s/Lf8A4N9v2avCPxe+LfjHxp4j07+1" +
			"NV+Hf9nSaJFMQ1rb3Fwbkm5KEfNLH9nXyyThCxbG9Y2T9SP2lv2avCP7Wfwk1HwX40077dpV9iSKWMhL" +
			"rTrhQQlzbuQdkqbjg4IIZlYMjMrFFY8N0YPKbOK15r6b779z0/HnMsXT8SOanVknS9jyNSa5Pdi/d193" +
			"Vt6W1be5/NZRRRX5cf6In//Z";
		
	}
}